version: '3'
services:
  intra-mongodb:
    container_name: intra-mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

  app:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - 80:8080
    command: mvn clean spring-boot:run
    depends_on:
      - intra-mongodb